import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Manually categorized (2026-08-31) -- the previous autogenerated sidebar put
// every doc in one flat list regardless of audience (a brand-guideline file
// next to the API reference, an M2M auth guide with no section heading at
// all). Real categories so someone can go straight to "just the API
// reference" instead of scanning five unrelated files.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['intro', 'USER_GUIDE'],
    },
    {
      type: 'category',
      label: 'Guides',
      items: ['guides/CLIENT_CREDENTIALS_INTEGRATION'],
    },
    {
      type: 'category',
      label: 'Reference',
      items: ['API_REFERENCE'],
    },
  ],
};

export default sidebars;
